Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09e67e426f25ce0d7 # Ubuntu Server 20.04 LTS (HVM), SSD Volume Type
      Tags:
        - Key: Name
          Value: "EC2 returns Public DNS"

Outputs:
  ServerDns:
    Value: !GetAtt
      - Ec2Instance
      - PublicDnsName
